/*
 * Pages
 * The control plane for Pages
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.nadr0j.pagesclient.api;

import com.github.nadr0j.pagesclient.ApiCallback;
import com.github.nadr0j.pagesclient.ApiClient;
import com.github.nadr0j.pagesclient.ApiException;
import com.github.nadr0j.pagesclient.ApiResponse;
import com.github.nadr0j.pagesclient.Configuration;
import com.github.nadr0j.pagesclient.Pair;
import com.github.nadr0j.pagesclient.ProgressRequestBody;
import com.github.nadr0j.pagesclient.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.github.nadr0j.pagesclient.model.Error;
import com.github.nadr0j.pagesclient.model.GetPageRequest;
import com.github.nadr0j.pagesclient.model.GetPageResponse;
import com.github.nadr0j.pagesclient.model.WritePageRequest;
import com.github.nadr0j.pagesclient.model.WritePageResponse;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class DefaultApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public DefaultApi() {
        this(Configuration.getDefaultApiClient());
    }

    public DefaultApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for pagesGetPagePost
     * @param getPageRequest Request body containing user, namespace, and page name. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetches a page. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid input, object invalid. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Page not found. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call pagesGetPagePostCall(GetPageRequest getPageRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = getPageRequest;

        // create path and map variables
        String localVarPath = "/pages/getPage";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call pagesGetPagePostValidateBeforeCall(GetPageRequest getPageRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'getPageRequest' is set
        if (getPageRequest == null) {
            throw new ApiException("Missing the required parameter 'getPageRequest' when calling pagesGetPagePost(Async)");
        }

        return pagesGetPagePostCall(getPageRequest, _callback);

    }

    /**
     * Gets a page.
     * Returns a previously written page based on user, namespace, and page name.
     * @param getPageRequest Request body containing user, namespace, and page name. (required)
     * @return GetPageResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetches a page. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid input, object invalid. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Page not found. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error. </td><td>  -  </td></tr>
     </table>
     */
    public GetPageResponse pagesGetPagePost(GetPageRequest getPageRequest) throws ApiException {
        ApiResponse<GetPageResponse> localVarResp = pagesGetPagePostWithHttpInfo(getPageRequest);
        return localVarResp.getData();
    }

    /**
     * Gets a page.
     * Returns a previously written page based on user, namespace, and page name.
     * @param getPageRequest Request body containing user, namespace, and page name. (required)
     * @return ApiResponse&lt;GetPageResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetches a page. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid input, object invalid. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Page not found. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<GetPageResponse> pagesGetPagePostWithHttpInfo(GetPageRequest getPageRequest) throws ApiException {
        okhttp3.Call localVarCall = pagesGetPagePostValidateBeforeCall(getPageRequest, null);
        Type localVarReturnType = new TypeToken<GetPageResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Gets a page. (asynchronously)
     * Returns a previously written page based on user, namespace, and page name.
     * @param getPageRequest Request body containing user, namespace, and page name. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetches a page. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid input, object invalid. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Page not found. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call pagesGetPagePostAsync(GetPageRequest getPageRequest, final ApiCallback<GetPageResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = pagesGetPagePostValidateBeforeCall(getPageRequest, _callback);
        Type localVarReturnType = new TypeToken<GetPageResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for pagesWritePagePost
     * @param writePageRequest Request body containing user, namespace, page name, and content. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully written or updated a page. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid input, object invalid. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Page already exists and overwriteExisting is false </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call pagesWritePagePostCall(WritePageRequest writePageRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = writePageRequest;

        // create path and map variables
        String localVarPath = "/pages/writePage";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call pagesWritePagePostValidateBeforeCall(WritePageRequest writePageRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'writePageRequest' is set
        if (writePageRequest == null) {
            throw new ApiException("Missing the required parameter 'writePageRequest' when calling pagesWritePagePost(Async)");
        }

        return pagesWritePagePostCall(writePageRequest, _callback);

    }

    /**
     * Writes a page.
     * Writes a new page or updates an existing page based on user, namespace, and page name.
     * @param writePageRequest Request body containing user, namespace, page name, and content. (required)
     * @return WritePageResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully written or updated a page. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid input, object invalid. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Page already exists and overwriteExisting is false </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error. </td><td>  -  </td></tr>
     </table>
     */
    public WritePageResponse pagesWritePagePost(WritePageRequest writePageRequest) throws ApiException {
        ApiResponse<WritePageResponse> localVarResp = pagesWritePagePostWithHttpInfo(writePageRequest);
        return localVarResp.getData();
    }

    /**
     * Writes a page.
     * Writes a new page or updates an existing page based on user, namespace, and page name.
     * @param writePageRequest Request body containing user, namespace, page name, and content. (required)
     * @return ApiResponse&lt;WritePageResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully written or updated a page. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid input, object invalid. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Page already exists and overwriteExisting is false </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<WritePageResponse> pagesWritePagePostWithHttpInfo(WritePageRequest writePageRequest) throws ApiException {
        okhttp3.Call localVarCall = pagesWritePagePostValidateBeforeCall(writePageRequest, null);
        Type localVarReturnType = new TypeToken<WritePageResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Writes a page. (asynchronously)
     * Writes a new page or updates an existing page based on user, namespace, and page name.
     * @param writePageRequest Request body containing user, namespace, page name, and content. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully written or updated a page. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid input, object invalid. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Page already exists and overwriteExisting is false </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call pagesWritePagePostAsync(WritePageRequest writePageRequest, final ApiCallback<WritePageResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = pagesWritePagePostValidateBeforeCall(writePageRequest, _callback);
        Type localVarReturnType = new TypeToken<WritePageResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
