/*
 * Pages
 * The control plane for Pages
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.pagesclient.api;

import com.example.pagesclient.ApiException;
import com.example.pagesclient.model.Error;
import com.example.pagesclient.model.GetPageRequest;
import com.example.pagesclient.model.GetPageResponse;
import com.example.pagesclient.model.WritePageRequest;
import com.example.pagesclient.model.WritePageResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Disabled
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    /**
     * Gets a page.
     *
     * Returns a previously written page based on user, namespace, and page name.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void pagesGetPagePostTest() throws ApiException {
        GetPageRequest getPageRequest = null;
        GetPageResponse response = api.pagesGetPagePost(getPageRequest);
        // TODO: test validations
    }

    /**
     * Writes a page.
     *
     * Writes a new page or updates an existing page based on user, namespace, and page name.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void pagesWritePagePostTest() throws ApiException {
        WritePageRequest writePageRequest = null;
        WritePageResponse response = api.pagesWritePagePost(writePageRequest);
        // TODO: test validations
    }

}
