/*
 * Pages
 * The control plane for Pages
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.pagesclient.model;

import com.example.pagesclient.model.Page;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetPageResponse
 */
public class GetPageResponseTest {
    private final GetPageResponse model = new GetPageResponse();

    /**
     * Model tests for GetPageResponse
     */
    @Test
    public void testGetPageResponse() {
        // TODO: test GetPageResponse
    }

    /**
     * Test the property 'page'
     */
    @Test
    public void pageTest() {
        // TODO: test page
    }

}
